-- ============================================================
--  COUNTER OS v2 - FERRERO ROCHER EDITION
--  CLEAN & WORKING SCHEMA - USE THIS ONE ONLY
--
--  ⚠️ IMPORTANT: This is the ONLY schema file you need
--  Delete SUPABASE_SCHEMA_FIXED.sql and SUPABASE_SCHEMA_FERRERO.sql
--
--  Run this ENTIRE file in Supabase SQL Editor
-- ============================================================

-- ============================================================
--  1. BUSINESS CATEGORIES (existing - for compatibility)
-- ============================================================
CREATE TABLE IF NOT EXISTS business_categories (
    code TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    emoji TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

INSERT INTO business_categories (code, label, emoji) VALUES
('agri', 'Agri Retailer', '🌱'),
('food', 'Food & Grocery', '🍱'),
('pharma', 'Pharmacy', '💊'),
('hardware', 'Hardware & Tools', '🔧'),
('textile', 'Textile & Fashion', '👗'),
('electronics', 'Electronics', '📱')
ON CONFLICT (code) DO NOTHING;


-- ============================================================
--  2. PROFILES TABLE (existing - updated for Ferrero)
-- ============================================================
CREATE TABLE IF NOT EXISTS profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    phone TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    shop TEXT NOT NULL,
    loc TEXT,
    cat TEXT REFERENCES business_categories(code) ON DELETE SET NULL,
    role TEXT NOT NULL CHECK (role IN ('retailer', 'distributor', 'admin')),
    wallet_balance NUMERIC(12,2) DEFAULT 0.0,
    payout_method TEXT DEFAULT 'upi',
    payout_detail TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE profiles REPLICA IDENTITY FULL;
CREATE INDEX IF NOT EXISTS idx_profiles_role ON profiles(role);
CREATE INDEX IF NOT EXISTS idx_profiles_phone ON profiles(phone);


-- ============================================================
--  3. FERRERO_PRODUCTS TABLE (NEW - Ferrero products catalog)
-- ============================================================
CREATE TABLE IF NOT EXISTS ferrero_products (
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    sku TEXT UNIQUE NOT NULL,
    description TEXT,
    category TEXT,
    unit TEXT DEFAULT 'Box',
    cost_price NUMERIC(10,2),
    retail_price NUMERIC(10,2),
    margin NUMERIC(5,2),
    image_url TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ferrero_products_sku ON ferrero_products(sku);
CREATE INDEX IF NOT EXISTS idx_ferrero_products_category ON ferrero_products(category);
CREATE INDEX IF NOT EXISTS idx_ferrero_products_active ON ferrero_products(is_active);


-- ============================================================
--  4. INVENTORY TABLE (existing - updated to reference ferrero_products)
-- ============================================================
CREATE TABLE IF NOT EXISTS inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    cat TEXT,
    unit TEXT,
    qty INTEGER DEFAULT 0,
    buy NUMERIC(10,2) DEFAULT 0.0,
    sell NUMERIC(10,2) DEFAULT 0.0,
    earn NUMERIC(10,2) DEFAULT 0.0,
    mfg TEXT,
    exp TEXT,
    business_cat TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_inventory_user_id ON inventory(user_id);
CREATE INDEX IF NOT EXISTS idx_inventory_created_at ON inventory(created_at);


-- ============================================================
--  5. OFFER_CAMPAIGNS TABLE (NEW - Ferrero campaigns)
-- ============================================================
CREATE TABLE IF NOT EXISTS offer_campaigns (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    description TEXT,
    offer_type TEXT NOT NULL CHECK (offer_type IN ('commission','discount','combo','cashback')),
    target_role TEXT NOT NULL CHECK (target_role IN ('retailer','distributor','all')),
    product_ids JSONB DEFAULT '[]'::jsonb,

    -- Commission fields
    commission_pct NUMERIC(5,2) DEFAULT 0,
    commission_min_qty INTEGER DEFAULT 1,

    -- Discount fields
    discount_pct NUMERIC(5,2) DEFAULT 0,
    discount_min_qty INTEGER DEFAULT 1,

    -- Combo fields
    combo_pct NUMERIC(5,2) DEFAULT 0,

    -- Cashback fields
    cashback_amount NUMERIC(10,2) DEFAULT 0,
    cashback_days INTEGER DEFAULT 7,

    -- Duration
    is_active BOOLEAN DEFAULT true,
    start_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    end_date TIMESTAMP WITH TIME ZONE,
    duration_days INTEGER DEFAULT 7,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE offer_campaigns REPLICA IDENTITY FULL;
CREATE INDEX IF NOT EXISTS idx_offer_campaigns_is_active ON offer_campaigns(is_active);
CREATE INDEX IF NOT EXISTS idx_offer_campaigns_target_role ON offer_campaigns(target_role);
CREATE INDEX IF NOT EXISTS idx_offer_campaigns_dates ON offer_campaigns(start_date, end_date);


-- ============================================================
--  6. CAMPAIGN_NOTIFICATIONS TABLE (NEW - Track claimed campaigns)
-- ============================================================
CREATE TABLE IF NOT EXISTS campaign_notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    campaign_id UUID NOT NULL REFERENCES offer_campaigns(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    is_claimed BOOLEAN DEFAULT false,
    claimed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(campaign_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_campaign_notifications_campaign_id ON campaign_notifications(campaign_id);
CREATE INDEX IF NOT EXISTS idx_campaign_notifications_user_id ON campaign_notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_campaign_notifications_claimed ON campaign_notifications(is_claimed);


-- ============================================================
--  7. COMMISSION_LEDGER TABLE (NEW - Track commissions)
-- ============================================================
CREATE TABLE IF NOT EXISTS commission_ledger (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    campaign_id UUID REFERENCES offer_campaigns(id) ON DELETE SET NULL,
    product_id TEXT,
    pieces_sold INTEGER,
    price_per_piece NUMERIC(10,2),
    commission_amount NUMERIC(12,2),
    cashback_amount NUMERIC(12,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_commission_ledger_user_id ON commission_ledger(user_id);
CREATE INDEX IF NOT EXISTS idx_commission_ledger_campaign_id ON commission_ledger(campaign_id);
CREATE INDEX IF NOT EXISTS idx_commission_ledger_created_at ON commission_ledger(created_at DESC);


-- ============================================================
--  8. WALLET_TRANSACTIONS TABLE (NEW - Track wallet activity)
-- ============================================================
CREATE TABLE IF NOT EXISTS wallet_transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    type TEXT NOT NULL CHECK (type IN ('commission','cashback','withdrawal','refund','credit','debit')),
    amount NUMERIC(12,2) NOT NULL,
    description TEXT,
    campaign_id UUID REFERENCES offer_campaigns(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_wallet_transactions_user_id ON wallet_transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_wallet_transactions_type ON wallet_transactions(type);
CREATE INDEX IF NOT EXISTS idx_wallet_transactions_created_at ON wallet_transactions(created_at DESC);


-- ============================================================
--  9. ORDERS TABLE (existing)
-- ============================================================
CREATE TABLE IF NOT EXISTS orders (
    id TEXT PRIMARY KEY,
    retailer_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
    retailer_name TEXT,
    items INTEGER DEFAULT 0,
    total NUMERIC(12,2) DEFAULT 0,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending','approved','fulfilled','rejected')),
    otp TEXT,
    items_list JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE orders REPLICA IDENTITY FULL;
CREATE INDEX IF NOT EXISTS idx_orders_retailer_id ON orders(retailer_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);


-- ============================================================
--  10. TRANSACTIONS TABLE (existing)
-- ============================================================
CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    type TEXT CHECK (type IN ('sale','purchase','cashback','refund')),
    label TEXT,
    sub TEXT,
    amt TEXT,
    clr TEXT,
    icon TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON transactions(user_id);


-- ============================================================
--  11. NOTIFICATIONS TABLE (existing)
-- ============================================================
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    body TEXT,
    type TEXT DEFAULT 'notification',
    offer_type TEXT,
    campaign_id UUID REFERENCES offer_campaigns(id) ON DELETE SET NULL,
    role TEXT CHECK (role IN ('retailer','distributor','admin')),
    is_read BOOLEAN DEFAULT false,
    read_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE notifications REPLICA IDENTITY FULL;
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_role ON notifications(role);
CREATE INDEX IF NOT EXISTS idx_notifications_is_read ON notifications(is_read);


-- ============================================================
--  12. CONNECTIONS TABLE (existing)
-- ============================================================
CREATE TABLE IF NOT EXISTS connections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    retailer_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    distributor_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(retailer_id, distributor_id)
);

CREATE INDEX IF NOT EXISTS idx_connections_retailer_id ON connections(retailer_id);
CREATE INDEX IF NOT EXISTS idx_connections_distributor_id ON connections(distributor_id);


-- ============================================================
--  ROW LEVEL SECURITY - ENABLE
-- ============================================================

ALTER TABLE business_categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE ferrero_products DISABLE ROW LEVEL SECURITY;
ALTER TABLE inventory DISABLE ROW LEVEL SECURITY;
ALTER TABLE offer_campaigns DISABLE ROW LEVEL SECURITY;
ALTER TABLE campaign_notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE commission_ledger DISABLE ROW LEVEL SECURITY;
ALTER TABLE wallet_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE connections DISABLE ROW LEVEL SECURITY;


-- ============================================================
--  REALTIME PUBLICATION
-- ============================================================

ALTER PUBLICATION supabase_realtime ADD TABLE offer_campaigns;
ALTER PUBLICATION supabase_realtime ADD TABLE campaign_notifications;
ALTER PUBLICATION supabase_realtime ADD TABLE notifications;
ALTER PUBLICATION supabase_realtime ADD TABLE orders;


-- ============================================================
--  SEED DATA - FERRERO PRODUCTS (14 products)
-- ============================================================

INSERT INTO ferrero_products (name, sku, description, category, unit, cost_price, retail_price, margin, is_active)
VALUES
('Ferrero Rocher 48 pieces', 'FR-48', 'Classic 48 piece box - premium hazelnut wafer', 'Rocher', 'Box', 300.00, 450.00, 50.00, true),
('Ferrero Rocher 16 pieces', 'FR-16', 'Premium hazelnut wafer - 16 piece pack', 'Rocher', 'Box', 110.00, 165.00, 50.00, true),
('Ferrero Rocher 8 pieces', 'FR-8', 'Individual premium pieces - 8 pack', 'Rocher', 'Pack', 60.00, 90.00, 50.00, true),
('Ferrero Rocher Single', 'FR-1', 'Single premium hazelnut piece', 'Rocher', 'Piece', 15.00, 25.00, 66.67, true),
('Golden Gallery 42 pieces', 'GG-42', 'Premium golden collection - 42 pieces', 'Golden Gallery', 'Box', 250.00, 375.00, 50.00, true),
('Golden Gallery 18 pieces', 'GG-18', 'Assorted golden chocolates - 18 pieces', 'Golden Gallery', 'Box', 120.00, 180.00, 50.00, true),
('Raffaello 42 pieces', 'RAF-42', 'Creamy coconut wafer - 42 piece box', 'Raffaello', 'Box', 280.00, 420.00, 50.00, true),
('Raffaello 20 pieces', 'RAF-20', 'Coconut specialty - 20 piece pack', 'Raffaello', 'Box', 145.00, 220.00, 51.72, true),
('Rondnoir 42 pieces', 'RND-42', 'Dark wafer specialty - 42 pieces', 'Rondnoir', 'Box', 280.00, 420.00, 50.00, true),
('Rondnoir 20 pieces', 'RND-20', 'Dark hazelnut & almond - 20 pieces', 'Rondnoir', 'Box', 145.00, 220.00, 51.72, true),
('Hazelnut Specialty Box', 'HNT-BOX', 'Premium hazelnut assortment - luxury pack', 'Hazelnut', 'Box', 320.00, 480.00, 50.00, true),
('Hazelnut Truffle Pieces', 'HNT-TRU', 'Single hazelnut truffle pieces - 10 count', 'Hazelnut', 'Pack', 80.00, 120.00, 50.00, true),
('Premium Assortment Box', 'PREM-BOX', 'Mixed premium selection - 60 pieces', 'Assortment', 'Box', 400.00, 600.00, 50.00, true),
('Holiday Gift Set', 'GIFT-SET', 'Special occasion luxury box - 80 pieces', 'Gift Set', 'Box', 500.00, 750.00, 50.00, true)
ON CONFLICT (sku) DO NOTHING;


-- ============================================================
--  SEED DATA - TEST USERS (7 profiles)
-- ============================================================

INSERT INTO profiles (phone, name, shop, loc, cat, role, wallet_balance)
VALUES
('9800000001', 'Rajesh Distributor', 'Rajesh Distributors', 'Indore, MP', 'food', 'distributor', 50000.00),
('9900000001', 'Ramesh Kumar', 'Kumar Sweet House', 'Khetgaon, MP', 'food', 'retailer', 5000.00),
('9900000002', 'Sunita Patel', 'Patel Gift Store', 'Dewas, MP', 'food', 'retailer', 3500.00),
('9900000003', 'Mohan Sharma', 'Sharma Confectionery', 'Ratlam, MP', 'food', 'retailer', 4200.00),
('9900000004', 'Anil Verma', 'Verma Premium Gifts', 'Sehore, MP', 'food', 'retailer', 2800.00),
('9900000005', 'Kavita Singh', 'Singh Luxury Sweets', 'Mandsaur, MP', 'food', 'retailer', 6100.00),
('9991111111', 'Admin Ferrero', 'CounterOS Admin', 'Headquarters', 'food', 'admin', 0.00)
ON CONFLICT (phone) DO NOTHING;


-- ============================================================
--  SAMPLE CAMPAIGN (1 test campaign)
-- ============================================================

INSERT INTO offer_campaigns (
    title, description, offer_type, target_role, product_ids, is_active,
    start_date, end_date, commission_pct, commission_min_qty, duration_days
) VALUES (
    '💰 Golden Commission Week',
    'Earn 8% extra commission on all Ferrero Rocher 48pc sales this week! Boost your earnings now.',
    'commission',
    'retailer',
    '[{"id":1,"name":"Ferrero Rocher 48 pieces","sku":"FR-48"}]'::jsonb,
    true,
    now(),
    now() + interval '7 days',
    8.00,
    15,
    7
)
ON CONFLICT DO NOTHING;


-- ============================================================
--  VERIFICATION QUERIES
-- ============================================================

-- Verify all tables exist
SELECT
    count(*) as "Total Tables"
FROM information_schema.tables
WHERE table_schema = 'public' AND table_type = 'BASE TABLE';

-- Verify Ferrero products
SELECT count(*) as "Ferrero Products" FROM ferrero_products;

-- Verify test users
SELECT count(*) as "Test Users" FROM profiles;

-- Verify campaigns
SELECT count(*) as "Sample Campaigns" FROM offer_campaigns;

-- List all tables (for final verification)
SELECT
    table_name
FROM information_schema.tables
WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
ORDER BY table_name;


-- ============================================================
--  SETUP COMPLETE
-- ============================================================
-- Tables created: 12
--   ✓ business_categories
--   ✓ profiles
--   ✓ ferrero_products
--   ✓ inventory
--   ✓ offer_campaigns (NEW)
--   ✓ campaign_notifications (NEW)
--   ✓ commission_ledger (NEW)
--   ✓ wallet_transactions (NEW)
--   ✓ orders
--   ✓ transactions
--   ✓ notifications
--   ✓ connections
--
-- Products: 14 Ferrero items
-- Users: 7 test profiles
-- Campaigns: 1 sample campaign
-- RLS: Disabled for development
-- Realtime: Enabled for campaigns & notifications
--
-- Your database is ready! 🍫✨
-- ============================================================
